<a href="https://colab.research.google.com/github/paulkennethjazul/Linear_Algebra_ChE_2nd_Sem_2021-2022/blob/main/Assignment_3_Matrix_in_Python.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Linear Algebra for Che
##Assignment 3 : Matrices

### Objectives
At the end of this activity you will be able to:
1. Be familiar with matrices and their relation to linear equations.
2. Perform basic matrix operations.
3. Program and translate matrix equations and operations using Python.


# Discussion

In [ ]:
import numpy as np
import matplotlib.pyplot as plt
import scipy.linalg as la
%matplotlib inline


## Matrices

The notation and use of matrices is probably one of the fundamentals of modern computing. Matrices are also handy representations of complex equations or multiple inter-related equations from 2-dimensional equations to even hundreds and thousands of them.

Let's say for example you have  and  as system of equation.

$$
A = \left\{
    \begin{array}\
        4x + 20y \\ 
        10x - 10y
    \end{array}
\right. \\
B = \left\{
    \begin{array}\
        11x+12y+13z \\ 
        5x -8y -9z \\
        -55x + 44y +22z
    \end{array}
\right. \\
C = \left\{
  \begin{array}\
  w - 21x + 35y - 45z \\
  3w - 21x - 22y + 20z \\
  2w - 9x + 10y - 11z
  \end{array}
\right. $$



$$
A=\begin{bmatrix} 1 & 1 \\ 4 & {-10}\end{bmatrix} \\
B=\begin{bmatrix} 1 & 1 & 1 \\ 3 & -2 & -1 \\ -1 & 4 & 2\end{bmatrix}\\
C=\begin{bmatrix} 1 & -2 & 3 & -4 \\ 3 & -1 & -2 & 1 \\ 2 & -1 & 3 & -2 \end{bmatrix}
$$




So assuming that you already discused the fundamental representation of matrices, their types, and operations. we'll proceed in doing them in here in Python

We could see that A is a system of 2 equations with 2 parameters 

## Declaring Matrices

Just like our previous laboratory activity, we'll represent system of linear equations as a matrix. The entities or numbers in matrices are called the elements of a matrix. These elements are arranged and ordered in rows and columns which form the list/array-like structure of matrices. And just like arrays, these elements are indexed according to their position with respect to their rows and columns. This can be reprsented just like the equation below. Whereas A is a matrix consisting of elements denoted by . Denoted by  is the number of rows in the matrix while  stands for the number of columns.

Do note that the  of a matrix is i x j .

$$A=\begin{bmatrix}
a_{(0,0)}&a_{(0,1)}&\dots&a_{(0,j-1)}\\
a_{(1,0)}&a_{(1,1)}&\dots&a_{(1,j-1)}\\
\vdots&\vdots&\ddots&\vdots&\\
a_{(i-1,0)}&a_{(i-1,1)}&\dots&a_{(i-1,j-1)}
\end{bmatrix}
$$


We already gone over some of the types of matrices as vectors but we'll further discuss them in this laboratory activity. Since you already know how to describe vectors using shape, dimensions and size attributes, we'll use them to analyze these matrices.

In [ ]:
## Since we'll keep on describing matrices. Lets make a function.
def describe_mat(matrix):
    print(f'Matrix:\n{matrix}\n\nShape:\t{matrix.shape}\nRank:\t{matrix.ndim}\n')


In [ ]:
## Declaring a 2 x 2 matrix
A = np.array ([
    [1, 2],
    [3, 1]
])
describe_mat(A)

Matrix:
[[1 2]
 [3 1]]

Shape:	(2, 2)
Rank:	2



In [ ]:
##Declaring a 2 x 3 matrix
G = np.array([
    [1,1,3],
    [2,2,4]
])
describe_mat(G)


Matrix:
[[1 1 3]
 [2 2 4]]

Shape:	(2, 3)
Rank:	2



In [ ]:
##Declaring a 3 x 2 matrix
B = np.array([
    [8, 2],
    [5, 4],
    [1, 1]
])
describe_mat(B)


Matrix:
[[8 2]
 [5 4]
 [1 1]]

Shape:	(3, 2)
Rank:	2



In [ ]:
H = np.array([1,2,3,4])
describe_mat(H)


Matrix:
[1 2 3 4]

Shape:	(4,)
Rank:	1



## Categorizing Matrices

There are several ways of classifying matrices. Once could be according to their shape and another is according to their element values. We'll try to go through them

### According to shape

#### Row and Column Matrices

Row and column are common in vector and matrix computations. They can also represent row and column spaces of a bigger vector space. Row and column spaces of a bigger vector space. Row and column matrices are represented by a single column or single row. So with that being, the shape of row matrices would be 1 x j  and column matrices would be i x 1 .

In [ ]:
## Declaring a Row Matrix

rowmatrix1D = np.array([
    1, 3, 2, -4
]) ## this is a 1-D Matrix with a shape of (3,), it's not really considered as a row matrix.
row_mat_2D = np.array([
    [1,2,3, -4]
]) ## this is a 2-D Matrix with a shape of (1,3)
describe_mat(rowmatrix1D)
describe_mat(row_mat_2D)


Matrix:
[ 1  3  2 -4]

Shape:	(4,)
Rank:	1

Matrix:
[[ 1  2  3 -4]]

Shape:	(1, 4)
Rank:	2



In [ ]:
##Declaring a Column Matrix
col_mat = np.array([
    [1],
    [2],
    [5]
]) ## this is a 2-D Matrix with a shape of (3,1)
describe_mat(col_mat)


Matrix:
[[1]
 [2]
 [5]]

Shape:	(3, 1)
Rank:	2



## Square Matrices

Square matrices are matrices that have the same row and column sizes. We could say a matrix is square if i = j . We can tweak our matrix descriptor function to determine square matrices.

In [ ]:
def describe_mat(matrix):
    is_square = True if matrix.shape[0] == matrix.shape[1] else False 
    print(f'Matrix:\n{matrix}\n\nShape:\t{matrix.shape}\nRank:\t{matrix.ndim}\nIs Square: {is_square}\n')


In [ ]:
square_mat = np.array([
    [1,2,5],
    [3,3,8],
    [6,1,2]
])

non_square_mat = np.array([
    [1,2,5],
    [3,3,8]
])
describe_mat(square_mat)
describe_mat(non_square_mat)


Matrix:
[[1 2 5]
 [3 3 8]
 [6 1 2]]

Shape:	(3, 3)
Rank:	2
Is Square: True

Matrix:
[[1 2 5]
 [3 3 8]]

Shape:	(2, 3)
Rank:	2
Is Square: False



### According to element values

### Null matrix
A Null Matrix is a matrix that has no elements. It is always a subspace of any vector or matrix.

In [ ]:
def describe_mat(matrix):
    if matrix.size > 1:
        is_square = False if matrix.shape[0] < matrix.shape[1] else False 
        print(f'Matrix:\n{matrix}\n\nShape:\t{matrix.shape}\nRank:\t{matrix.ndim}\nIs Square: {is_square}\n')
    else:
        print('Matrix is Null')


In [ ]:
null_mat = np.array([])
describe_mat(null_mat)

Matrix is Null


### Zero Matrix

A zero matrix can be any rectangular matrix but with all elements having a value of 0.

In [ ]:
zero_mat_row = np.zeros((1,1))
zero_mat_sqr = np.zeros((3,3))
zero_mat_rct = np.zeros((4,4))

print(f'Zero Row Matrix: \n{zero_mat_row}')
print(f'Zero Square Matrix: \n{zero_mat_sqr}')
print(f'Zero Rectangular Matrix: \n{zero_mat_rct}')


Zero Row Matrix: 
[[0.]]
Zero Square Matrix: 
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
Zero Rectangular Matrix: 
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


### Ones Matrix
A ones matrix, just like the zero matrix, can be any rectangular matrix but all of its elements are 1s instead of 0s.

In [ ]:
ones_mat_row = np.ones((1,3))
ones_mat_sqr = np.ones((2,3))
ones_mat_rct = np.ones((4,4))

print(f'Ones Row Matrix: \n{ones_mat_row}')
print(f'Ones Square Matrix: \n{ones_mat_sqr}')
print(f'Ones Rectangular Matrix: \n{ones_mat_rct}')


Ones Row Matrix: 
[[1. 1. 1.]]
Ones Square Matrix: 
[[1. 1. 1.]
 [1. 1. 1.]]
Ones Rectangular Matrix: 
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


### DIagonal Matrix

A diagonal matrix is a square matrix that has values only at the diagonal of the matrix.

In [ ]:
np.diag([
    [2,0,0],
    [0,3,0],
    [0,0,5]
])

array([2, 3, 5])

### Identity Matrix

An identity matrix is a special diagonal matrix in which the values at the diagonal are ones.

In [ ]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
np.identity(4)


array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

### Upper Triangular Matrix

An upper triangular matrix is a matrix that has no values below the diagonal.

In [ ]:
P = np.array([
    [1,2,3,4],
    [1,3,1,-1],
    [1,1,5,2],
    [1,1,1,2]
])
np.triu(P)

array([[ 1,  2,  3,  4],
       [ 0,  3,  1, -1],
       [ 0,  0,  5,  2],
       [ 0,  0,  0,  2]])

In [ ]:
F = np.array([
              [2, -3, 4, -5, 6],
              [2, -3, 4, -5, 6],
              [2, -3, 4, -5, 6],
              [2, -3, 4, -5, 6],
              [2, -3, 4, -5, 6],
])
np.triu(F)


array([[ 2, -3,  4, -5,  6],
       [ 0, -3,  4, -5,  6],
       [ 0,  0,  4, -5,  6],
       [ 0,  0,  0, -5,  6],
       [ 0,  0,  0,  0,  6]])

###Lower Triangular Matrix

A lower triangular matrix is a matrix that has no values above the diagonal.

In [ ]:
E = np.array([
              [2, -3, 4, -5, 6],
              [2, -3, 4, -5, 6],
              [2, -3, 4, -5, 6],
              [2, -3, 4, -5, 6],
              [2, -3, 4, -5, 6],
])
np.tril(E)


array([[ 2,  0,  0,  0,  0],
       [ 2, -3,  0,  0,  0],
       [ 2, -3,  4,  0,  0],
       [ 2, -3,  4, -5,  0],
       [ 2, -3,  4, -5,  6]])

In [ ]:
G = np.array([
   [1,0,0],
   [5,3,0],
   [7,8,9]
])
np.tril(G)

array([[1, 0, 0],
       [5, 3, 0],
       [7, 8, 9]])

###Practice

1. Given the linear combination below, try to create a corresponding matrix representing it.


:$$\theta = 10x + 66y - 99z$$


2. Given the system of linear combinations below, try to encode it as a matrix. Also describe the matrix.


$$
A = \left\{\begin{array}
55x_1 + 4x_2 +2x_3\\
6x_2 - 5x_3\\
20x_3
\end{array}\right.
$$


3. Given the matrix below, express it as a linear combination in a markdown and a LaTeX markdown


In [ ]:
G = np.array([
    [1,7,8],
    [2,2,2],
    [4,6,7]
])
G

array([[1, 7, 8],
       [2, 2, 2],
       [4, 6, 7]])

4. Given the matrix below, display the output as a LaTeX markdown also express it as a system of linear combinations.


In [ ]:
H = np.tril(G)
H


array([[1, 0, 0],
       [2, 2, 0],
       [4, 6, 7]])

###Addition

In [ ]:
A = np.array ([
    [6,2,4],
    [5,3,8],
    [3,6,8] 
])
B = np.array([
    [2,5,3],
    [6,9,6],
    [7,8,9]
])
A+B

array([[ 8,  7,  7],
       [11, 12, 14],
       [10, 14, 17]])

### Substraction


In [ ]:
A-B-A


array([[-2, -5, -3],
       [-6, -9, -6],
       [-7, -8, -9]])

In [ ]:
5-B


array([[ 3,  0,  2],
       [-1, -4, -1],
       [-2, -3, -4]])

### Multiplication

In [ ]:
A*B


array([[12, 10, 12],
       [30, 27, 48],
       [21, 48, 72]])

###Element wise multiplication

In [ ]:
np.multiply(A,B)


array([[12, 10, 12],
       [30, 27, 48],
       [21, 48, 72]])

###Element wise division

In [ ]:
np.divide(A,B)

array([[3.        , 0.4       , 1.33333333],
       [0.83333333, 0.33333333, 1.33333333],
       [0.42857143, 0.75      , 0.88888889]])

#Task 1

Create a function named mat_desc() that througouhly describes a matrix, it should:

Displays the shape, size, and rank of the matrix.

Displays whether the matrix is square or non-square.

Displays whether the matrix is an empty matrix.

Displays if the matrix is an identity, ones, or zeros matrix


Use 5 sample matrices in which their shapes are not lower than . In your methodology, create a flowchart discuss the functions and methods you have done. Present your results in the results section showing the description of each matrix you have declared.

In [ ]:
## Function Area
def mat_desc(mat):
    sq = False
    mat = np.array(mat)
    print(mat)
    print('Shape:', mat.shape)
    print('Size:', mat.size)
    print('Rank:', np.linalg.matrix_rank(mat))
    if(mat.shape[0] == mat.shape[1]):
        sq = True
        print('The matrix is square')
    else:
        print('The matrix is non-square')
    if(mat.shape[0] == 0 and mat.shape[1] == 0):
        print('The matrix is empty')
    else:
        print('The matrix is not empty')
    iden = np.identity(mat.shape[0])
    if(sq and (iden == mat).all()):
        print('The matrix is an identity matrix')
    else:
        print('The matrix is not an identity matrix')
    one = np.ones((mat.shape[0], mat.shape[1]))
    if((one == mat).all()):
        print('The matrix is an ones matrix')
    else:
        print('The matrix is not an ones matrix')
    zero = np.zeros((mat.shape[0], mat.shape[1]))
    if((zero == mat).all()):
        print('The matrix is an zeros matrix')
    else:
        print('The matrix is not a zeros matrix')

In [ ]:
## Matrix Declarations

Q = np.array([
    [3,4,6],
    [7,8,9],
    [2,3,1]          
])

G = np.array([
    [4,5,7],
    [8,9,6],
    [2,3,1]        
])


P = np.array([
    [1,1,1],
    [1,1,1],
    [1,1,1]        
])

Z = np.array([
    [3,3,3],
    [3,3,3],
    [3,3,3]           
])

I = np.array([
    [0,0,0],
    [0,0,0],
    [0,0,0],
              
])

T = np.array([
    [1., 0., 0.],
    [0., 1., 0.],
    [0., 0., 1.]
])

In [ ]:
##Test Areas

mat_desc(Q)

mat_desc(G)

mat_desc(P)

mat_desc(Z)

mat_desc(I)

mat_desc(T)

[[3 4 6]
 [7 8 9]
 [2 3 1]]
Shape: (3, 3)
Size: 9
Rank: 3
The matrix is square
The matrix is not empty
The matrix is not an identity matrix
The matrix is not an ones matrix
The matrix is not a zeros matrix
[[4 5 7]
 [8 9 6]
 [2 3 1]]
Shape: (3, 3)
Size: 9
Rank: 3
The matrix is square
The matrix is not empty
The matrix is not an identity matrix
The matrix is not an ones matrix
The matrix is not a zeros matrix
[[1 1 1]
 [1 1 1]
 [1 1 1]]
Shape: (3, 3)
Size: 9
Rank: 1
The matrix is square
The matrix is not empty
The matrix is not an identity matrix
The matrix is an ones matrix
The matrix is not a zeros matrix
[[3 3 3]
 [3 3 3]
 [3 3 3]]
Shape: (3, 3)
Size: 9
Rank: 1
The matrix is square
The matrix is not empty
The matrix is not an identity matrix
The matrix is not an ones matrix
The matrix is not a zeros matrix
[[0 0 0]
 [0 0 0]
 [0 0 0]]
Shape: (3, 3)
Size: 9
Rank: 0
The matrix is square
The matrix is not empty
The matrix is not an identity matrix
The matrix is not an ones matrix
The mat

#Task 2

Create a function named mat_operations() that takes in two matrices a input parameters it should:

Determines if the matrices are viable for operation and returns your own error message if they are not viable.

Returns the sum of the matrices.

Returns the difference of the matrices.

Returns the element-wise multiplication of the matrices.

Returns the element-wise division of the matrices.

Use 5 sample matrices in which their shapes are not lower than . In your methodology, create a flowchart discuss the functions and methods you have done. Present your results in the results section showing the description of each matrix you have declared.

In [ ]:
def mat_operations(matrix):
  print (f'{matrix}')

In [ ]:
import numpy as np
import matplotlib.pyplot as plt
import scipy.linalg as la
%matplotlib inline

In [101]:
## Matrix 1
row1 = int(input("enter the row number of the first matrix: " ))
col1 = int(input("enter the column number of the first matrix: "))

print('enter', row1*col1, 'elements for matrix 1: ')
matrix1 = list(map(int, input().split()))
r_matrix1 = np.array(matrix1).reshape(row1,col1)
print("matrix 1 is: ")
mat_operations(r_matrix1)

## Matrix 2
row2 = int(input("\nenter the row number of the second matrix: " ))
col2 = int(input("enter the column number of the second matrix: "))

print('enter', row2*col2, 'elements for matrix 2: ')
matrix2 = list(map(int, input().split()))
r_matrix2 = np.array(matrix2).reshape(row2,col2)
print("matrix 2 is: ")
mat_operations(r_matrix2)

## Matrix 3
row3 = int(input("\nenter the row number of the third matrix: " ))
col3 = int(input("enter the column number of the third matrix: "))

print('enter', row3*col3, 'elements for matrix 3: ')
matrix3 = list(map(int, input().split()))
r_matrix3 = np.array(matrix3).reshape(row3,col3)
print("matrix 3 is: ")
mat_operations(r_matrix3)

first = r_matrix1
second = r_matrix2
third = r_matrix3
### ADDITION ----------------------------------------------------------------
print('\nselect two matrices to to add. (Note: use first, second, third, to select the matrices)')
firstadd = str(input("matrix #: "))
print('+') 
secondadd =str(input("matrix #: "))

result = (eval(firstadd).shape == eval(secondadd).shape)
if result:
  print('\nThe sum of the',firstadd,'and',secondadd,'matrix is: ')
  print(eval(firstadd)+eval(secondadd))
else:
  print('\nOperation not viable, check matrix dimensions.') 

###SUBTRACTION--------------------------------------------------------------
print('\nselect two matrices to to subtract')
firstsubb = str(input("matrix #: ")) 
print('-') 
secondsubb =str(input("matrix #: "))

result = (eval(firstsubb).shape == eval(secondsubb).shape)
if result:
  print('\nThe difference of the',firstsubb,'and',secondsubb,'matrix is: ')
  print(eval(firstsubb)-eval(secondsubb))
else:
  print('\nOperation not viable, check matrix dimensions.') 

###ELEMENT-WISE MULTIPLICATION----------------------------------------------
print('\nselect two matrices to multiply')
firstmult = str(input("matrix #: "))
print('x') 
secondmult =str(input("matrix #: "))

result = (eval(firstmult).shape == eval(secondmult).shape)
if result:
  print('\nThe product of the',firstmult,'and',secondmult,'matrix is: ')
  print(eval(firstmult)*eval(secondmult))
else:
  print('\nOperation not viable, check matrix dimensions.') 

### ELEMENT-WISE DIVISION --------------------------------------------------
print('\nselect two matrices to divide')
firstdiv = str(input("matrix #: "))
print('/')
seconddiv =str(input("matrix #: "))

result = (eval(firstdiv).shape == eval(seconddiv).shape)
if result:
  print('\nThe product of the',firstdiv,'and',seconddiv,'matrix is: ')
  print(eval(firstdiv)/eval(seconddiv))
else: 
  print('\nOperation not viable, check matrix dimensions.') 

enter the row number of the first matrix: 2
enter the column number of the first matrix: 2
enter 4 elements for matrix 1: 
2 2 2 2
matrix 1 is: 
[[2 2]
 [2 2]]

enter the row number of the second matrix: 2
enter the column number of the second matrix: 2
enter 4 elements for matrix 2: 
2 2 2 2
matrix 2 is: 
[[2 2]
 [2 2]]

enter the row number of the third matrix: 2
enter the column number of the third matrix: 2
enter 4 elements for matrix 3: 
2 2 2 2
matrix 3 is: 
[[2 2]
 [2 2]]

select two matrices to to add. (Note: use first, second, third, to select the matrices)
matrix #: first + second
+
matrix #: second + third

The sum of the first + second and second + third matrix is: 
[[8 8]
 [8 8]]

select two matrices to to subtract
matrix #: first
-
matrix #: second

The difference of the first and second matrix is: 
[[0 0]
 [0 0]]

select two matrices to multiply
matrix #: first
x
matrix #: second

The product of the first and second matrix is: 
[[4 4]
 [4 4]]

select two matrices to divi